configurations/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [	
    url(r'^intranethszone/', admin.site.urls),
    url(r'',include('intranet.urls')),
    url(r'iands/',include('gp.urls')),		
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.STATIC_ROOT})	
]

gp/urls.py
from django.conf.urls import url
from gp.views import PostComplaint ,LoginView,ViewComplaintByDomain,HomeView,Upvotes,viewMyComplaints
from django.conf import settings

urlpatterns = [
			url(r'complaint/post/$',PostComplaint.as_view(),name = 'postcomplaint'),
			url(r'$',LoginView.as_view(),name = 'login'),
			url(r'complaints/view/$',ViewComplaintByDomain.as_view(),name= 'complaints'),
			url(r'^accounts/home/$',HomeView.as_view(),name='homepage'),
			url(r'upvote/complaint/$',Upvotes,name = 'upvote'),
			url(r'mycomplaints/$',viewMyComplaints.as_view(),name='mycomplaints'),		
		]

gp/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Domain(models.Model):
	name = models.CharField(max_length = 100, primary_key=True)
	description = models.TextField()
	Incharge = models.TextField()
	def __str__(self):
		return self.name

class group(models.Model):
	name = models.TextField()


class UserProfile(models.Model):
	GENDER = (('M','Male'),('F','Female'),)
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	gender = models.CharField(max_length=2,choices=GENDER)
	groupset = models.TextField()


class Complaint(models.Model):
	STATUS = (('Registered','Registered'),('Assigned','Assigned'),('Solved','Solved'),('Closed','Closed'),)
	title = models.CharField(max_length=200)
	description = models.TextField()
	domain = models.ForeignKey(Domain, on_delete = models.CASCADE)
	posted_by = models.ForeignKey(User, on_delete = models.CASCADE)
	upvotes = models.PositiveIntegerField(default = 0)
	#downvotes = models.PositiveIntegerField(default = 0)
	status = models.CharField(max_length = 30,choices = STATUS,default = 'Registered')
	who_can_see = models.CharField(max_length = 2,choices = (('All','Everybody'),('F','Faculty')))
	solved  = models.BooleanField(default = False)
	approved = models.BooleanField( default= False)
	posted_on = models.DateTimeField(auto_now = True)
	def __str__(self):
			return str(self.title)

	def upvote(self):
		self.upvotes +=1
		return self.upvotes	

	def getUpvotes(self):
		return self.upvotes	

class Solution(models.Model):
	complaint = models.ForeignKey(Complaint, on_delete = models.CASCADE)
	solution = models.TextField()
	author = models.ForeignKey(User)
	given_on = models.DateTimeField(auto_now = True)

class Suggestion(models.Model):
	complaint = models.ForeignKey(Complaint,on_delete = models.CASCADE)
	author = models.ForeignKey(User, related_name="gp_suggestion", on_delete = models.CASCADE)
	suggestion = models.TextField()	
	upvotes = models.PositiveIntegerField()
	downvotes = models.PositiveIntegerField()


class Upvote(models.Model):
	cid = models.ForeignKey(Complaint, on_delete = models.CASCADE)
	uid = models.ForeignKey(User, on_delete = models.CASCADE)

	class Meta:
		unique_together = ('cid','uid')

gp/forms.py
from django import forms
from django.contrib.auth.forms import *
from django.contrib.auth.models import User
from gp.models import Domain
from gp.methods import get_list_of_domains

class LoginForm(AuthenticationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'mdl-textfield__input', 'id':'username'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'mdl-textfield__input', 'id':'password'}))
	

class postComplaintForm(forms.Form):
	#domain = forms.ChoiceField(choices = get_list_of_domains(), widget=forms.RadioSelect(attrs={'class':'mdl-radio__button'}))
	domain = forms.ChoiceField(choices = [], widget=forms.RadioSelect(attrs={'class':'mdl-radio__button'}))
	title = forms.CharField(widget=forms.TextInput(attrs={'class':'mdl-textfield__input'}))
	hostel = forms.ChoiceField(label='',choices = (('gh','Girls Hostel'),('bh','Boys Hostel')),widget=forms.RadioSelect(attrs={'class':'mdl-radio__button','id':'radio-hostel'}))
	description = forms.CharField(widget = forms.Textarea(attrs={'class':'mdl-textfield__input','rows':'5'}))

gp/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User
from gp.models import Complaint, Domain, Upvote
from gp.forms import LoginForm, postComplaintForm
from django.utils import timezone
from django.contrib.auth import login
from django.contrib.auth import logout
from gp.methods import Is_incharge
from django.http import HttpResponse
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.core.mail import send_mail


# Create your views here.
class LoginView(FormView):
	form_class = LoginForm
	template_name = 'login.html'
	success_url = '/accounts/home/'

	def dispatch(self,*args,**kwargs):
		return super(LoginView,self).dispatch(*args,**kwargs)

	def get_context_data(self,**kwargs):
		context = super(LoginView,self).get_context_data(**kwargs)
		return context	

	def form_valid(self,form):
		login(self.request, form.get_user())
		success_url = '/accounts/home/'

		return super(LoginView,self).form_valid(form)

	def form_invalid(self,form):
		return self.render_to_response(self.get_context_data(form=form))


class HomeView(TemplateView):
	template_name ='home.html'

	def dispatch(self,*args,**kwargs):
		return super(HomeView,self).dispatch(*args,**kwargs)

	def get_context_data(self,**kwargs):
		context = super(HomeView,self).get_context_data(**kwargs)

class PostComplaint(FormView):
	form_class = postComplaintForm
	template_name = 'post_complaint.html'
	success_url = '/complaints/view/'
	
	def dispatch(self,*args,**kwargs):
		return super(PostComplaint,self).dispatch(*args,**kwargs)
	
	def form_valid(self,form):
			domain = form.cleaned_data['domain'].encode('utf-8')
			try:
				domain_obj = Domain.objects.get(name=str(domain))
			except DoesNotExist:
				domain_obj= Domain.objects.all()[0] 

				
			title = form.cleaned_data['title'].encode('utf-8')
			description = form.cleaned_data['description'].encode('utf-8')
			#send_mail('Issue Registered in the portal.Sub = '+title , description,'IandS@iiits.in',domain_obj.Incharge.split(','),fail_silently = False)
			c = Complaint(title=title,description=description,domain=domain_obj,posted_by = self.request.user)
			c.save()
			redirect_to = self.success_url
			return super(PostComplaint,self).form_valid(form)

	def get_context_data(self, **kwargs):
			context = super(PostComplaint,self).get_context_data(**kwargs)
			return context 

	def form_invalid(self,form):
			return self.render_to_response(self.get_context_data(form=form))	



class ViewComplaintByDomain(TemplateView):
	template_name = 'complaints.html'

	def dispatch(self,*args,**kwargs):
		return super(ViewComplaintByDomain,self).dispatch(*args,**kwargs)

	def get_context_data(self,**kwargs):
		context = super(ViewComplaintByDomain,self).get_context_data(**kwargs)
		get_by_domain = self.request.GET.get('get_by_domain')

		if get_by_domain == 'All' or get_by_domain == None:
			c = Complaint.objects.all()

		else:
			c = Complaint.objects.filter(domain = get_by_domain)
	

		context['complaints'] = c	
		
		return context


class viewMyComplaints(TemplateView):
	template_name = 'mycomplaint.html'

	def dispatch(self,*args,**kwargs):
		return super(viewMyComplaints,self).dispatch(*args,**kwargs)

	def get_context_data(self,**kwargs):
		context = super(viewMyComplaints,self).get_context_data(**kwargs)
		user = self.request.user
		c = Complaint.objects.filter(posted_by = user)

		context['mycomplaints'] = c 
		
		return context


def Upvotes(request):
	 
	 ID = request.GET.get('ID')
	 c = Complaint.objects.get(id=int(ID))
	 userId = request.user
	 try:
	 	up = Upvote(cid = c, uid = userId)
	 	up.save()
	 	cup = c.upvote()
	 	c.save()
	 	return HttpResponse(cup)
	 except IntegrityError:
			return HttpResponse("You already upvoted,"+str(c.getUpvotes()))
	 
	 

			

	 

gp/templates/complaints.html
{% extends 'home.html'%}
{% load staticfiles %}

{% block main %}

	<span class="mdl-layout-title">Complaints</span>
	{% for x in complaints%}
	<center>
	<div class="demo-card-wide mdl-card mdl-shadow--2dp" style="width:550px;margin-top:10px;">
		<div class="mdl-card__title mdl-card--expand" style="color:blue;height:176px;margin-top:0;">
			<h4>
				{{x.domain}} <br> 
				{{x.title}}<br>
				I Support : {{x.upvotes}} <br>
				DATE : {{x.posted_on|date:"d-m-y"}}

			</h4>
			
		</div>
		<div class="mdl-card__supporting-text">
			<b>{{x.description}}</b>
		</div>
		<div class="mdl-card__actions mdl-card--border">
    		<a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
      Upvote
    </a>
  </div>	
	</div>	
</center>
<br>
{% endfor %}
{% endblock %}	

gp/templates/home.html
{% load staticfiles %}
<html>
    {% include 'resources.html' %}

<body>
    <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
      <header class="demo-header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">I&amp;S Portal</span>
          <div class="mdl-layout-spacer"></div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
          </div>
          <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
            <i class="material-icons">more_vert</i>
          </button>
          <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
            <li class="mdl-menu__item">Edit Profile</li>
            <li class="mdl-menu__item">Change Password</li>
            <li class="mdl-menu__item">Sign Out</li>
          </ul>
        </div>
      </header>
      <div class="demo-drawer mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
        <header class="demo-drawer-header">
          <img src="images/user.jpg" class="demo-avatar">
        </header>
        <nav class="demo-navigation mdl-navigation mdl-color--blue-grey-800">
          <a class="mdl-navigation__link" href="/accounts/home"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">home</i>Home</a>
          <a class="mdl-navigation__link" href="/complaint/post"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">feedback</i>Post a complaint</a>
          <a class="mdl-navigation__link" href="/mycomplaints"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">inbox</i>View My Complaints</a>
          <div class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">forum</i>View Complaints

        <div >
          <div class="mdl-layout-spacer"></div>
         <div class="bar">
                 
               <button id="demo_menu-lower-right" class="mdl-button mdl-js-button mdl-button--icon" data-upgraded=",MaterialButton">
                  <i class="material-icons">more_vert</i>
               </button>
               <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                  for="demo_menu-lower-right">
                  <a href = "/complaints/view/?get_by_domain=All"><li class="mdl-menu__item">All</li></a>
                  <a href = "/complaints/view/?get_by_domain=Academic"><li class="mdl-menu__item">Academic</li></a>
                  <a href = "/complaints/view/?get_by_domain=Mess"><li class="mdl-menu__item">Mess</li></a>
                  <a href = "/complaints/view/?get_by_domain=Hostel"><li class="mdl-menu__item">Hostel</li></a>   
               </ul>
            
         </div>
         <div class="background"></div>
      </div>

          </div>
          <div class="mdl-layout-spacer"></div>
          <a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">help_outline</i><span class="visuallyhidden">Help</span></a>
        </nav>
      </div>
      {% block main %}
      {% endblock %}
      {% block Issueform%}
      {% endblock%}
</body>      

gp/templates/login.html
{% load staticfiles %}
<html>
    {% include 'resources.html' %}


<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class = "mdl-layout__header mdl-layout__header">
      <center><span class="mdl-layout-title" style="font-size:30px;margin-top:10px;"> I &amp; S Portal</span></center>
    </header>
	
<center>
  <br>
  <br>
<div class="mdl-card mdl-shadow--2dp">
			<div class="mdl-card__title">
          		<h2 class="mdl-card__title-text">Please Login</h2>
          	</div>
  			<div class="mdl-card__supporting-text">
  				<form action="" method="post">
          			{%csrf_token%}
					{% if form.non_field_errors %}
						{{ form_error }}
					{% endif %}
  					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    					{{form.username}}
    					<label class="mdl-textfield__label" for="username">Enter your Email...</label>
  					</div>
          			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    					{{form.password}}
    					<label class="mdl-textfield__label" for="password">Enter your password...</label>
  					</div>
  					<button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect">
  					Login
					</button>
				</form>
			</div>
		</div>
	</center>	
	
</div>

gp/templates/mycomplaints.html
{% extends 'home.html'%}
{% load staticfiles %}

<span class="mdl-layout-title">Complaints</span>
	{% for x in mycomplaints%}
	<center>
	<div class="demo-card-wide mdl-card mdl-shadow--2dp" style="width:550px;margin-top:10px;">
		<div class="mdl-card__title mdl-card--expand" style="color:blue;height:176px;margin-top:0;">
			<h4>
				{{x.domain}} <br> 
				{{x.title}}<br>
				I Support : {{x.upvotes}} <br>
				DATE : {{x.posted_on|date:"d-m-y"}}

			</h4>
			
		</div>
		<div class="mdl-card__supporting-text">
			<b>{{x.description}}</b>
		</div>
		<div class="mdl-card__actions mdl-card--border">
    		<a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
      Upvote
    </a>
  </div>	
	</div>	
</center>
<br>
{% endfor %}

gp/templates/passwordchange.html
{% load staticfiles%}
{% include 'resources.html'%}

<body>
	
</body>

gp/templates/post_complaint.html
{%extends 'home.html'%}
{% load staticfiles %}

{% block Issueform%}
<center>
<h3 style="color:blue;"> Post an Issue</h3>
<form action="" method="post">{% csrf_token%}
  <div class="mdl-textfield mdl-js-textfield">
    {{form.title}}
    <label class="mdl-textfield__label">Enter the title...</label>
  </div>
  <br>
  <br>
 {%for i in form.domain%}
  	<label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" style="margin:5px;">
  		{{i}}
  	</label>
 {%endfor%}
 <br>
 <br>
<div class="mdl-textfield mdl-js-textfield">
  	{{form.description}}
  	<label class="mdl-textfield__label">Write about the issue here...</label>
</div>
<br>
<br>
<button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect">
 POST
</button>
</form>
</center>
<script>
$(document).ready(function(){
	$('#radio-hostel').hide();
	$('#id_domain').on('change',function(){	
	var domainval = $('#id_domain').val();
	
	if(domainval== 'Hostel'){
		$('#radio-hostel').show();
	}
	else{
		$('#radio-hostel').hide();
	}
	});
});
</script>
{% endblock%}  

gp/templates/resources.html
{% load staticfiles %}
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>I&amp;S Portal</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/android-desktop.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

	<!--<link rel="stylesheet" type="text/css" href="{% static 'gp/css/bootstrap.min.css'%}" /> -->
	<link rel="stylesheet" type="text/css" href="{% static 'gp/css/material.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'gp/css/style.css'%}">	
	<link rel="stylesheet" type="text/css" href="{% static 'gp/css/font-awesome.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'gp/css/styles.css'%}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<!--<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.1/material.cyan-light_blue.min.css">
	-->
	<script src="{% static 'gp/js/jquery.min.js' %}"></script>
	<!--<script src="{% static 'gp/js/bootstrap.min.js' %}"></script>-->
	<script src="{% static 'gp/js/script.js' %}"></script>
	<script src="{% static 'gp/js/material.min.js' %}"></script>
		<style>
    #view-source {
      position: fixed;
      display: block;
      right: 0;
      bottom: 0;
      margin-right: 40px;
      margin-bottom: 40px;
      z-index: 900;
    }
    </style>
</head>